apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskproducer
spec:
  selector:
    matchLabels:
      app: flaskproducer
  template:
    metadata:
      labels:
        app: flaskproducer
    spec:
      containers:
      - name: flaskproducer
        image: winatan/flaskproducer
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
 name: flaskproducer
spec:
 type: NodePort
 selector:
   app: flaskproducer
 ports:
 - port: 80
   targetPort: 5000
   nodePort: 31290